### ISSUE TITLE
How to call the API `hoodie.store(options)` returns?

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/wip-hoodie-store-on-pouchdb#42]
I have trouble with finding a clear name for the API that `hoodie.store(options)` returns. 

What it does: The default use case is to pass a string, which  returns a subset of the hoodie.store API. All methods are scoped to objects with the 'type' property set to the passed string, e.g. `hoodie.store("todo")`:

```js
var todoStore = hoodie.store('todo')
todoStore.add({name: 'test'})
// {name: 'test', type: 'todo'}

todoStore.on('add', log)
hoodie.store.add({foo: 'bar'}
// does not log
hoodie.store.add({foo: 'bar', type: 'test'}
// does log
```

But more options could be passed to hoodie.store():

```js
hoodie.store({type: 'config', id: 'app'})
// all methods scoped to one specific object
// has no add / findAll / updateAll / removeAll methods

hoodie.store({validate: validateFunction})
// custom validation function run for all methods that do changes

hoodie.store({name: 'custo-db-name'})
// opens new local database 'hoodie-store-custom-db-name' that is physically separated from hoodie.store’s default database ('hoodie-store'). When replicated, it tries to create /hoodie/store/custom-db-name

hoodie.store({name: {
  local: 'm-public-data',
  remote: 'user/abc1234/public'
}})
// just as above, with different names for local / remote databases
```

Passing more options than the type as string is currently out of scope
for this repository. We might even decide to make it out of scope for
the `hoodie.store` API itself, and instead provide a plugin for the
other options. But either way, naming things is hard, and this thing
in particular led to confusion in the past. Plus I needed to
put this thoughts somewhere™

**Comment by gr2m** [comment]
By far the most common usage will be just to pass a string, to get a store API that is scoped to objects with the according type property value. All the MV* frameworks that have the concept of collections will do that in the their adapters, and if an app has more than one object type, it'd need to do it as well. So something like this would become very common

```js
hoodie.store('todo').on('change', renderTodoList)
hoodie.store('todo').add({title: 'test'})
hoodie.store('todo').findAll().then(renderTodoList)
```

You could write the same as

```js
todoStore = hoodie.store('todo');
todoStore.on('change', renderTodoList)
todoStore.add({title: 'test'})
todoStore.findAll().then(renderTodoList)
```

But it won't make any difference.

This is a very common usage in Hoodie today, and I wouldn't make it more complex by adding an extra method for it. I think `hoodie.store('todo').on('change', renderTodoList)` reads easier than `hoodie.store.scope('todo').on('change', renderTodoList)`, the latter might be more self explanatory though, plus we'd call the thing that it returns "scoped store" when talking about it. In that case, I'd leave out the option to pass a `name` option to open a different database, and put that into a plugin.

A common request for current Hoodie was to pass a custom validation method though, think something like this:

```js
var todoStore = hoodie.store({type: 'todo', validate: function(object) {
  if (! object.title) return 'title must be set';
});
todoStore.add({foo: 'bar'}).catch(function(error) {
  // error.message is "title must be set"
});
```

So `todoStore` would be more than just a scoped store, it would also have custom behavior. Validation is a topic on its own and we will add server-side validation anyway, but that shouldn't stop us from providing a simple front-end API anyway, there are valid use cases for it in any case.

Sorry for the long comment :/ here's my **tl;dr** so far

1. we call the returned API "scoped store"
2. we leave out the `name` option and put it in a separate plugin
3. we add a `hoodie.store.scoped(options)` method, or leave it as is: `hoodie.store(options)`

**Comment by janl** [comment]
How about `hoodie.store(type[, options])`?

**Comment by janl** [comment]
(thanks for the great explanation)

**Comment by gr2m** [comment]
> How about `hoodie.store(type[, options])`?

We'll also need a scoped store for both type & id. Passing id as part of `options` would be odd. Also, I can think of use cases where I don't want to pass a `type`, but only a validation method. So we'd need 

- `hoodie.store(options)`
- `hoodie.store(type[, options])`
- `hoodie.store(type, id[, options])`

That's what we have today, by the way (without the options argument). I think it would be more clear to have 

- `hoodie.store(type)` for most of the cases
- `hoodie.store(options)` when necessary. 

Because 

```js
hoodie.store({type: 'config', id: 'app', validate: validateConfig})
```

explains itself better than 

```js
hoodie.store('config', 'app', {validate: validateConfig})
```

**Comment by janl** [comment]
Squaring a circle, eh? :)

Named parameters (via the options object) are definitely better long term. Are there other places in the API that could do with this treatment, or that already use this convention? Symmetry would be worth achieving.

I’m wondering if we can make it a documentation solution. E.g. allow all of the above, but never show the `(type, id, options)`.

**Comment by gr2m** [comment]
> Squaring a circle

Always ;)

We could make it a documentation solution, by supporting `(type, id, options)` without documenting it. But it's a hidden complexity, we'd need to take care of it with everything we do in future, to not break it, although we don't show it anywhere in the docs. I'm not sure if it's worth it in this particular case.

**Comment by janl** [comment]
Right, the alternative is `store(type || object)` — if that’s good enough for you for the general case(s), that’d work for me.

**Comment by gr2m** [comment]
:+1:

**Comment by snnd** [comment]
I like the idea with options as last parameter. Reminds me a lot to the Ruby on Rails api back than.

>    we call the returned API "scoped store"

`hoodie.store` to me was always more similiar to a context/manager factory. Once you call `hoodie.store('type')` you have a context/manager object that operates on `type`. Since `hoodie.store('type', 'id')` seems be the same as `hoodie.store('type').find('id');`, the shorter version was just syntax candy to me. 

I don't know how confusing the multiple ways of doing the same thing, appear to a beginner or non-coder.

With the factory idea in mind I think the following could be charming:

```js
var optionalStoreOptions = {
  validate: recipeValidation
  local: 'm-public-data',
  remote: 'user/abc1234/public'
};

hoodie
    .store('recipe', optionalStoreOptions)
    .find('cheesecake')
    .then(translateReceipe)
    .done(displayReceipe);

```
The seperation into configuration and operation syntax, comes closer to real world examples like "open the book 'receipe' and `findOrAdd` the 'cheesecake' receipe". Also how to tell someone why it is sometimes the one way and sometimes the other way to non coder. A single straight forward rule could be a simplification to the better here. 

Just 2 cents.

Regards,
Dennis

**Comment by gr2m** [comment]
> Since hoodie.store('type', 'id') seems be the same as hoodie.store('type').find('id');, the shorter version was just syntax candy to me. 

That is not quite right. `hoodie.store('type', 'id')` returns a a store API without  `add`, `findAll`, `removeAll`, `updateAll` methods, and `on` being scoped to only the one specific object, while `hoodie.store('type').find('id')` returns a promise that resolves if the object exists, otherwise rejects. `hoodie.store('type').find('id');` would be the same as `hoodie.store('type', 'id').find();`, maybe that's what you meant?

@snnd To follow up on your suggestion, would you agree that if we go the "options as last parameter" way, both `type` and `id` would be optional, so we could do this: `myStore = hoodie.store({validate: myValidateMethod})`?

**Comment by snnd** [comment]
Yes I agree. Actually `type` as first parameter in hoodie.store could be confused for a `storeName` anyways, so it is probably nice to have the alternate `hoodie.store({validate:..}).find(type, id)`.

Will hoodie have multiple stores in future or will we stick to a single store per user?

**Comment by gr2m** [comment]
this is related: https://github.com/hoodiehq/discussion/issues/67

**Comment by gr2m** [comment]
> Will hoodie have multiple stores in future or will we stick to a single store per user?

every user will have one mirrored database, that won't change. But there will be ways to make other databases available offline as well, or to store objects in a separate local database, for objects that should not be synced, etc. But this functionality doesn't need to be covered by the `hoodie.store` API, it can be put in a plugin, as the use cases won't be as common

**Comment by gr2m** [comment]
So we after half a year, we are now building this for real, adding it to https://github.com/hoodiehq/pouchdb-hoodie-store. 

It's just a gut feeling, but I prefer `hoodie.store.scoped("todo")` over `hoodie.store("todo")` now. It's more expressive. Any thoughts?

PS: I love this issue is #42 :P

**Comment by gr2m** [comment]
closing in favor of https://github.com/hoodiehq/hoodie-client-store/issues/55
