### ISSUE TITLE
Local config storage

### ISSUE THREAD

**Issue by nickcolley** [hoodiehq/wip-hoodie-store-on-pouchdb#43]
Noticed this issue on the main repo: https://github.com/hoodiehq/hoodie.js/issues/398 

With PouchDB you can store local non-replicating data using a document with an id "_local" http://docs.couchdb.org/en/latest/api/local.html

Not sure if it makes sense for this use case as I'm not familiar with the main hoodie.js codebase so apologies in advance.

**Comment by gr2m** [comment]
That's interesting, I didn't actually know the `_local` API. But we need a synchronous API for config to provide a simple API, so I fear this will not suite for it. But thanks!

**Comment by janl** [comment]
Would faking a blocking API on top of this work?

**Comment by gr2m** [comment]
How would you fake a blocking API on top of this?

**Comment by janl** [comment]
hackery with timeouts and all.

**Comment by janl** [comment]
sorry, don’t mind me, I keep forgetting how JavaScript works.
