### ISSUE TITLE
use PouchDB's new `denied` & and `change` events for sync

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/wip-hoodie-store-on-pouchdb#45]
we currently use a fork of PouchDB, which we now can get rid of, as these have been merged into master:
- https://github.com/pouchdb/pouchdb/pull/3292
- https://github.com/pouchdb/pouchdb/pull/3375

They will most likely land in PouchDb 3.2.2

**Comment by janl** [comment]
👏👏👏

**Comment by timblack1** [comment]
I think that means you can change https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb/blob/master/package.json#L26, right?

**Comment by gr2m** [comment]
the implementation that landed in PouchDB is slightly different if I remember correctly, we must adapt it first

**Comment by timblack1** [comment]
I'm trying to figure out what needs to be done here.  Does this issue mean we need to change

```javascript
    sync.on('error', defer.reject);
```
to
```javascript
    sync.on('denied', defer.reject);
```
and
```javascript
    sync.on('replicated', function(change) {
```
to
```javascript
    sync.on('change', function(change) {
```
?

Do you intend to use PouchDB's new plural change.docs data inside the listener to the `'change'` event?  Looking at the code in api.js, I don't think that would be necessary.

**Comment by gr2m** [comment]
@timblack1 Yes. We are currently creating another plugin that has only the sync methods over at https://github.com/gr2m/pouchdb-hoodie-sync. Just getting started. But together with https://github.com/hoodiehq/pouchdb-hoodie-api, and a wrapper around these two PouchDB plugins, we'll have the new `hoodie.store` API :)

**Comment by timblack1** [comment]
Thanks @gr2m!  Your comment above plus https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb/issues/40#issuecomment-96219978 is the status report I've been looking for, because (I think) it tells me how you (currently) intend to tie the components together into a final working version of Hoodie using PouchDB.

**Comment by gr2m** [comment]
Hey @timblack, I'll close this as I think it's obsolete, but things are moving in Hoodie/PouchDB land, see http://gr2m.github.io/milestones/. Best is to ping me in the #hoodie-pouch slack channel for farther questions
