### ISSUE TITLE
hoodie.js contains merge conflicts

### ISSUE THREAD

**Issue by timblack1** [hoodiehq/wip-hoodie-store-on-pouchdb#46]
The current version of github.com/gr2m/hoodie.js#pouchdb at https://github.com/gr2m/hoodie.js/blob/pouchdb/dist/hoodie.js#L560 contains merge conflicts.  Could you resolve the conflicts?

**Comment by timblack1** [comment]
I don't know hoodie.js very well, but it looks to me like the <<<<<<< HEAD sections are completely out of context, so do not belong in the file.

**Comment by gr2m** [comment]
@timblack1 that's correct. Don't use the dist files, we'll get rid of them. Thanks for bringing that to our attention :)

Load hoodie directly from the Hoodie server at `/_api/_files/hoodie.js`.

**Comment by timblack1** [comment]
Ok, thanks.  Now I know to edit the source files if I need to change what is served from `/_api/_files/hoodie.js`.

**Comment by janl** [comment]
they live in node_modules/hoodie-server/hoodie/ and node_modules/hoodie-plugin-*/hoodie.*.js
