### ISSUE TITLE
401 Unauthorized error

### ISSUE THREAD

**Issue by timblack1** [hoodiehq/wip-hoodie-store-on-pouchdb#47]
I'm using hoodie-store-pouchdb (https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb) with https://github.com/hoodiehq/grunt-hoodie, and when I call hoodie.store.connect() in my JavaScript console, I get the following error.

`XMLHttpRequest cannot load http://localhost:6001/user%2fbaerthf/?_nonce=hnTmmFCumuTA7BAP. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:9000' is therefore not allowed access.`

Grunt serves my Hoodie app's www interface at http://localhost:9000, and from that origin my code (a Polymer element named &lt;hoodie-service&gt;) calls `this.hoodie = new Hoodie('http://localhost:6001');` to initialize Hoodie.  CouchDB is accessible at http://localhost:6003 and http://localhost:6001/_api.

What appears to be the problem is that https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb/blob/master/lib/index.js#L35 feeds PouchDB's lib/adapters/http/http.js a URL missing the "/_api" part, so the error above is generated because the URL doesn't lead to CouchDB's location.  When I add "/_api" to the URL there, it appears that Hoodie talks to CouchDB but then I get a new error:

`GET http://localhost:6001/_api/user%2fbaerthf/?_nonce=G2doG9d7wSxHblUd 401 (Unauthorized)`

At that URL, CouchDB's literal response is:

`{"error":"unauthorized","reason":"You are not authorized to access this db."}`

My browser was sending a lot of cookies for localhost, so I deleted them and tried again.  After that, the browser sent no cookies, and only sent the nonce.  But I still got the same error.

**Comment by gr2m** [comment]
Hoodie doesn't work directly against a CouchDB, it needs a Hoodie server. When you use grunt-hoodie, you can simply do `this.hoodie = new Hoodie();`, without passing the URL. `grunt-hoodie` set up a proxy at `/_aip`

**Comment by timblack1** [comment]
I got it running.  What I had to do was insert this before module.exports in my Gruntfile.js:

`var proxySnippet = require('grunt-connect-proxy/lib/utils').proxyRequest;`

then call it in livereload:

```javascript
      livereload: {
        options: {
          middleware: function (connect) {
            return [
              lrSnippet,
              mountFolder(connect, '.tmp'),
              mountFolder(connect, yeomanConfig.app),
              proxySnippet
            ];
          }
        }
      },
```
then insert `configureProxies:serve` and move `hoodie:start` BEFORE `configureProxies:serve` and `connect:livereload`:

```javascript
  grunt.registerTask('serve', function (target) {
    if (target === 'dist') {
      return grunt.task.run(['build', 'open', 'connect:dist:keepalive']);
    }

    grunt.task.run([
      'clean:server',
      'sass:server',
      'copy:styles',
      'autoprefixer:server',
      'hoodie:start',
      'configureProxies:serve',
      'connect:livereload',
      'hoodiejs',
      'open',
      'watch'
    ]);
  });
```
I don't know Grunt really well, but it seems to me this might mean you need to update https://github.com/hoodiehq/grunt-hoodie/blob/master/README.md.
