### ISSUE TITLE
IndexedDB & CouchDB don't sync

### ISSUE THREAD

**Issue by timblack1** [hoodiehq/wip-hoodie-store-on-pouchdb#48]
I must be misunderstanding something here, but I can't get the data I've inserted into IndexedDB using this version of Hoodie to sync to CouchDB.

While logged in to Hoodie, I inserted data into PouchDB/IndexedDB like this:  `hoodie.store.add({type:'testing',name:'testing'})`.  The new data objects show up in Chrome DevTools' Resources tab's IndexedDB in the database named `_pouch_/user%2f64bshoa`.

Then I look in the CouchDB database named `user%2F64bshoa` (which Hoodie created) using the following temporary view in Futon and it returns zero results:

```javascript
function(doc) {
  if (doc.type == 'testing'){emit(null, doc);}
}
```

The same thing happens after I run sync commands like the following in the browser console:

```javascript
hoodie.store.connect()
hoodie.store.sync()
hoodie.store.push()
hoodie.store.pull()
```

I ran this repository's tests, and they all passed both in the browser and in node, so what am I doing wrong?

One difference from https://github.com/hoodiehq/wip-hoodie-store-on-pouchdb/blob/master/package.json is that I changed line 26 to read `"pouchdb": "latest"` and ran `npm update`, but I had the same problem before I made that change.

**Comment by gr2m** [comment]
I think we should be good now with https://github.com/hoodiehq/hoodie-server-store & https://github.com/hoodiehq/hoodie-client-store
